import { EnumOptions, registerEnumType } from '@nestjs/graphql';
import { Logger } from '@nestjs/common';

/**
 * Configuration options for dynamic enum registration
 */
export interface DynamicEnumOptions<T extends object> {
  /**
   * The name of the enum in GraphQL schema
   */
  name: string;

  /**
   * Overall description for the enum
   */
  description?: string;

  /**
   * Custom descriptions for each enum value
   * @example { DRAFT: 'Posts in draft state', PUBLISHED: 'Published posts' }
   */
  customDescriptions?: Partial<Record<keyof T, string>>;

  /**
   * Auto-generate human-readable descriptions from enum keys
   * @default true
   * @example USER_ROLE -> 'User Role'
   */
  autoGenerateDescriptions?: boolean;

  /**
   * Prefix for auto-generated descriptions
   * @example 'Status: ' -> 'Status: Draft'
   */
  descriptionPrefix?: string;

  /**
   * Deprecate specific enum values
   * @example { OLD_STATUS: 'Use NEW_STATUS instead' }
   */
  deprecationReasons?: Partial<Record<keyof T, string>>;

  /**
   * Enable debug logging for registration
   * @default false
   */
  debug?: boolean;
}

/**
 * Transform enum key to human-readable format
 * @example 'USER_ROLE' -> 'User Role'
 * @example 'PENDING_APPROVAL' -> 'Pending Approval'
 */
function formatEnumKey(key: string): string {
  return key
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Validate enum reference
 */
function validateEnum<T extends object>(enumRef: T, name: string): void {
  if (!enumRef || typeof enumRef !== 'object') {
    throw new Error(
      `[DynamicRegisterEnum] Invalid enum reference for "${name}". Expected an object.`,
    );
  }

  const values = Object.values(enumRef);
  if (values.length === 0) {
    throw new Error(
      `[DynamicRegisterEnum] Enum "${name}" has no values. Cannot register empty enum.`,
    );
  }
}

/**
 * Enhanced dynamic enum registration utility
 *
 * Features:
 * - Auto-generates human-readable descriptions
 * - Supports custom descriptions per value
 * - Deprecation support
 * - Type-safe
 * - Debug logging
 * - Validation
 *
 * @example Basic usage
 * ```typescript
 * enum PostStatus {
 *   DRAFT = 'DRAFT',
 *   PUBLISHED = 'PUBLISHED'
 * }
 *
 * dynamicRegisterEnum(PostStatus, {
 *   name: 'PostStatus',
 *   description: 'Post publication status'
 * });
 * ```
 *
 * @example Advanced usage with custom descriptions
 * ```typescript
 * dynamicRegisterEnum(UserRole, {
 *   name: 'UserRole',
 *   description: 'User roles in the system',
 *   customDescriptions: {
 *     ADMIN: 'Administrator with full access',
 *     USER: 'Regular user with limited access'
 *   },
 *   deprecationReasons: {
 *     OLD_ROLE: 'Use ADMIN instead'
 *   },
 *   debug: true
 * });
 * ```
 */
export function dynamicRegisterEnum<T extends object>(
  enumRef: T,
  options: DynamicEnumOptions<T>,
): void {
  const logger = new Logger('DynamicRegisterEnum');
  const {
    name,
    description,
    customDescriptions = {},
    autoGenerateDescriptions = true,
    descriptionPrefix = '',
    deprecationReasons = {},
    debug = false,
  } = options;

  try {
    // Validate enum
    validateEnum(enumRef, name);

    // Build values map with descriptions
    const valuesMap: Record<
      string,
      { description?: string; deprecationReason?: string }
    > = {};
    const enumKeys = Object.keys(enumRef) as Array<keyof T>;
    const enumValues = Object.values(enumRef);

    // Only process string enums (skip numeric enum keys)
    const stringKeys = enumKeys.filter((key) => typeof key === 'string');

    stringKeys.forEach((key) => {
      const value = enumRef[key] as string;

      // Skip if value is not in the enum values (handles numeric enums)
      if (!enumValues.includes(value)) {
        return;
      }

      let valueDescription: string | undefined;

      // 1. Check for custom description
      const customDesc = (customDescriptions as any)[key];
      if (customDesc) {
        valueDescription = customDesc;
      }
      // 2. Auto-generate description
      else if (autoGenerateDescriptions) {
        const formatted = formatEnumKey(String(key));
        valueDescription = descriptionPrefix
          ? `${descriptionPrefix}${formatted}`
          : formatted;
      }

      // Build value config
      valuesMap[value] = {
        description: valueDescription,
      };

      // Add deprecation if specified
      const deprecationReason = (deprecationReasons as any)[key];
      if (deprecationReason) {
        valuesMap[value].deprecationReason = deprecationReason;
      }
    });

    // Register enum with GraphQL
    registerEnumType(enumRef, {
      name,
      description,
      valuesMap: valuesMap as any,
    });

    // Debug logging
    if (debug) {
      logger.debug(`✅ Registered enum "${name}"`);
      logger.debug(`   Values: ${Object.keys(valuesMap).join(', ')}`);
      logger.debug(`   Total: ${Object.keys(valuesMap).length}`);
    }
  } catch (error) {
    logger.error(`❌ Failed to register enum "${name}": ${error.message}`);
    throw error;
  }
}

/**
 * Batch register multiple enums at once
 *
 * @example
 * ```typescript
 * batchRegisterEnums([
 *   { enumRef: PostStatus, options: { name: 'PostStatus' } },
 *   { enumRef: UserRole, options: { name: 'UserRole' } },
 *   { enumRef: CommentStatus, options: { name: 'CommentStatus' } }
 * ]);
 * ```
 */
export function batchRegisterEnums<T extends object>(
  enums: Array<{ enumRef: T; options: DynamicEnumOptions<T> }>,
): void {
  const logger = new Logger('BatchRegisterEnums');

  logger.log(`Registering ${enums.length} enum(s)...`);

  let successCount = 0;
  let failureCount = 0;

  enums.forEach(({ enumRef, options }) => {
    try {
      dynamicRegisterEnum(enumRef, options);
      successCount++;
    } catch (error) {
      failureCount++;
      logger.error(`Failed to register enum "${options.name}"`);
    }
  });

  logger.log(
    `✅ Batch registration complete: ${successCount} success, ${failureCount} failed`,
  );
}

/**
 * Register enum with minimal configuration (quick helper)
 *
 * @example
 * ```typescript
 * quickRegisterEnum(PostStatus, 'PostStatus');
 * ```
 */
export function quickRegisterEnum<T extends object>(
  enumRef: T,
  name: string,
  description?: string,
): void {
  dynamicRegisterEnum(enumRef, {
    name,
    description,
    autoGenerateDescriptions: true,
  });
}
