/**
 * Example: Centralized Enum Registration
 *
 * This file demonstrates how to register all enums in one place
 * for better organization and maintenance.
 *
 * Usage: Import and call this function at app initialization
 */

import {
  batchRegisterEnums,
  dynamicRegisterEnum,
} from './dynamic-register-enum';

// Import all your enums
import { PostStatusFilter } from '../../modules/post/dto/post-filters.dto';

/**
 * Example enums (you would import these from your actual modules)
 */
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
  GUEST = 'GUEST',
}

export enum CommentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SPAM = 'SPAM',
}

export enum CategoryType {
  TECHNOLOGY = 'TECHNOLOGY',
  LIFESTYLE = 'LIFESTYLE',
  BUSINESS = 'BUSINESS',
  ENTERTAINMENT = 'ENTERTAINMENT',
  EDUCATION = 'EDUCATION',
}

export enum NotificationFrequency {
  REAL_TIME = 'REAL_TIME',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  NEVER = 'NEVER',
}

/**
 * Register all enums using batch registration
 *
 * This is the recommended approach for projects with many enums
 */
export function registerAllEnums() {
  batchRegisterEnums<
    | typeof UserRole
    | typeof CommentStatus
    | typeof CategoryType
    | typeof NotificationFrequency
  >([
    // User-related enums
    {
      enumRef: UserRole,
      options: {
        name: 'UserRole',
        description: 'User roles and permission levels',
        customDescriptions: {
          SUPER_ADMIN: 'Super administrator with unrestricted access',
          ADMIN: 'Administrator with full system access',
          MODERATOR: 'Moderator who can manage content',
          USER: 'Regular user with standard permissions',
          GUEST: 'Guest user with read-only access',
        },
      },
    },

    // Content-related enums
    {
      enumRef: CommentStatus,
      options: {
        name: 'CommentStatus',
        description: 'Comment moderation status',
        customDescriptions: {
          PENDING: 'Comment awaiting moderator review',
          APPROVED: 'Comment approved and visible to all',
          REJECTED: 'Comment rejected by moderator',
          SPAM: 'Comment marked as spam',
        },
      },
    },

    {
      enumRef: CategoryType,
      options: {
        name: 'CategoryType',
        description: 'Blog post category types',
        autoGenerateDescriptions: true, // Auto-converts TECHNOLOGY -> "Technology"
      },
    },

    // Notification-related enums
    {
      enumRef: NotificationFrequency,
      options: {
        name: 'NotificationFrequency',
        description: 'How often users receive notifications',
        customDescriptions: {
          REAL_TIME: 'Receive notifications immediately as they happen',
          HOURLY: 'Receive a summary of notifications every hour',
          DAILY: 'Receive a daily digest of notifications',
          WEEKLY: 'Receive a weekly summary of notifications',
          NEVER: 'Never receive notifications (disabled)',
        },
      },
    },
  ]);
}

/**
 * Alternative: Register enums individually with more control
 */
export function registerEnumsIndividually() {
  // User Role with deprecation
  dynamicRegisterEnum(UserRole, {
    name: 'UserRole',
    description: 'User roles and permission levels',
    customDescriptions: {
      SUPER_ADMIN: 'Super administrator with unrestricted access',
      ADMIN: 'Administrator with full system access',
      MODERATOR: 'Moderator who can manage content',
      USER: 'Regular user with standard permissions',
      GUEST: 'Guest user with read-only access',
    },
    deprecationReasons: {
      GUEST:
        'Guest role is being phased out. Use USER with limited permissions instead.',
    },
    debug: process.env.NODE_ENV === 'development',
  });

  // Comment Status with prefix
  dynamicRegisterEnum(CommentStatus, {
    name: 'CommentStatus',
    description: 'Comment moderation status',
    descriptionPrefix: 'Status: ',
  });

  // Category Type - simple auto-generation
  dynamicRegisterEnum(CategoryType, {
    name: 'CategoryType',
    description: 'Blog post category types',
    autoGenerateDescriptions: true,
  });

  // Notification Frequency with detailed descriptions
  dynamicRegisterEnum(NotificationFrequency, {
    name: 'NotificationFrequency',
    description: 'Notification delivery frequency settings',
    customDescriptions: {
      REAL_TIME: 'Instant notifications (push, email, SMS)',
      HOURLY: 'Hourly digest (email only)',
      DAILY: 'Daily digest at 9 AM (email only)',
      WEEKLY: 'Weekly digest on Monday (email only)',
      NEVER: 'All notifications disabled',
    },
  });
}

/**
 * Example: Register only critical enums first,
 * then register optional ones later
 */
export function registerCriticalEnums() {
  // Register only the most important enums
  batchRegisterEnums([
    {
      enumRef: UserRole,
      options: {
        name: 'UserRole',
        description: 'User roles',
      },
    },
    // PostStatusFilter is already registered in its own file
  ]);
}

export function registerOptionalEnums() {
  // Register nice-to-have enums
  batchRegisterEnums<typeof CategoryType | typeof NotificationFrequency>([
    {
      enumRef: CategoryType,
      options: {
        name: 'CategoryType',
        description: 'Category types',
      },
    },
    {
      enumRef: NotificationFrequency,
      options: {
        name: 'NotificationFrequency',
        description: 'Notification frequency',
      },
    },
  ]);
}

/**
 * Usage in your app:
 *
 * Option 1: Register all at once (recommended)
 * ```typescript
 * // In AppModule or main.ts (before GraphQL schema builds)
 * import { registerAllEnums } from './common/registers/register-all-enums';
 * registerAllEnums();
 * ```
 *
 * Option 2: Register in stages
 * ```typescript
 * registerCriticalEnums();
 * // ... later
 * registerOptionalEnums();
 * ```
 *
 * Option 3: Register individually as needed
 * ```typescript
 * // In each module's DTO file
 * import { dynamicRegisterEnum } from '@common/registers/dynamic-register-enum';
 * dynamicRegisterEnum(MyEnum, { ... });
 * ```
 */
